version:  "3"

services:  
  prometheus:
    image: prom/prometheus
    extra_hosts:
      - "devopsyy.ir:192.168.122.117"
      - "up.devopsyy.ir:192.168.122.117"
      - "metrics.devopsyy.ir:192.168.122.117"
      - "monitor.devopsyy.ir:192.168.122.117"
    volumes:
      - ./volumes/prometheus/data/:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: always
