version: "3"

services:
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - 127.0.0.1:9100:9100
    pid: host
    restart: unless-stopped
    entrypoint: [ "/bin/node_exporter", "--web.telemetry-path=/node_exporter/metrics" ]
    volumes:
      - /var/log/backup:/var/log/backup
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.textfile.directory=/var/log/backup'
