all:
  children:
    matrix:
      children:
        ins_a:
          hosts:
            ins_a_synapse:
              ansible_ssh_host: 192.168.122.120
              ansible_ssh_port: 33022
              matrix_instance: insa.ir
        ins_b:
          hosts:
            ins_b_synapse:
              ansible_ssh_host: 192.168.122.130
              ansible_ssh_port: 50079
              matrix_instance: insb.ir
      vars:
        app_update_api_path: /root/infra/services/matrix/app_update_api

    backup:
      children:
        ins_a_backup:
          hosts:
            srvpayamena_backup_ins_a:
              ansible_ssh_host: 94.10.10.216
              ansible_ssh_port: 8080
              backup_path_matrix: "/home/abbasi/backup/matrix"
            srvparsonline_backup_ins_a:
              ansible_ssh_host: 10.10.10.10
              ansible_ssh_port: 50078
              backup_path_matrix: "/root/backup/matrix"
          vars:
              matrix_instance: insa.ir
        ins_b_backup:
          hosts:
            srvpayamena_backup_ins_b:
              ansible_ssh_host: 94.10.10.216
              ansible_ssh_port: 8080
              backup_path_matrix: "/home/abbasi/backup/matrix"
            srvparsonline_backup_ins_b:
              ansible_ssh_host: 10.10.10.10
              ansible_ssh_port: 50078
              backup_path_matrix: "/root/backup/matrix"
          vars:
              matrix_instance: insb.ir
  vars:
    ansible_ssh_user: root
