version:  "3"

services:  
  grafana:
    image: grafana/grafana:10.0.1
    user: "root"
    ports:
      - 127.0.0.1:3005:3000
    environment:
      - GF_AUTH_PROXY_ENABLED=true
      - GF_SERVER_ROOT_URL=https://monitor.devopsyy.ir
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./volumes/grafana_data:/var/lib/grafana
      - /etc/hosts:/etc/hosts:ro
    restart: always
