#!/usr/bin/env ansible-playbook
---
- name: Copy synapse env
  become: true
  tags:
    - copy_synapse_env
  template:
    src: "env.synapse.j2"
    dest: "{{ tools_path }}/matrix/synapse/.env"
    owner: root
    group: root
    mode: 0644

- name: docker pull synapse
  command: "docker pull docker.{{ domain }}/matrixdotorg/synapse:{{ SYNAPSE_VERSION }}"
  args:
    chdir: "{{ tools_path }}"

- name: generate synapse config
  command: "docker run -it --rm --mount type=volume,src=infra_synapse_data,dst=/data -e SYNAPSE_SERVER_NAME={{ domain }} -e SYNAPSE_REPORT_STATS=no docker.{{ domain }}/matrixdotorg/synapse:{{ SYNAPSE_VERSION }} generate"
  args:
    chdir: "{{ tools_path }}"

- name: docker compose down api
  command: 'docker compose down'
  args:
    chdir: "{{ tools_path }}/matrix/synapse"

- name: docker compose up api
  command: 'docker compose up -d'
  args:
    chdir: "{{ tools_path }}/matrix/synapse"
