version: "3"
services:
  nginx:
    image: nginx:1.23.1
    restart: always
    extra_hosts:
      - "devopsyy.ir:192.168.122.117"
      - "up.devopsyy.ir:192.168.122.117"
      - "metrics.devopsyy.ir:192.168.122.117"
      - "monitor.devopsyy.ir:192.168.122.117"
    network_mode: host
#    ports:
#      - ${HTTP_PORT}:80
#      - ${HTTPS_PORT}:443
    volumes:
      - ./volumes/html:/usr/share/nginx/html:ro
      - ./volumes/html:/etc/nginx/html:ro
      - ./files/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./files/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./files/certbot:/etc/letsencrypt:ro
      - ./files/vhost.d:/etc/nginx/vhost.d:ro
#      - ./files/modules:/usr/lib/nginx/modules:ro
