version: "3"

# test with https://up.devopsyy.ir/probe?target=matrix.azadresan.ir&module=http_2xx&debug=true
services:
  blackbox:
    image: prometheus/blackbox-exporter:latest
    extra_hosts:
      - "devopsyy.ir:192.168.122.117"
      - "up.devopsyy.ir:192.168.122.117"
      - "metrics.devopsyy.ir:192.168.122.117"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blackbox_exporter
    restart: always
    tty: true
    volumes:
      - ./:/config
    ports:
      - 9115:9115/tcp
    command:
      - --config.file=/config/blackbox.yml
