# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "insa.lr"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
database:
  name: sqlite3
  args:
    database: /data/homeserver.db
log_config: "/data/insa.lr.log.config"
media_store_path: /data/media_store
registration_shared_secret: "8K;FZc:KTSD8N7iAUl1e~.wk~wF+&HTvxF~FkF:1xG0HmB_LF9"
report_stats: false
macaroon_secret_key: "FT9;0ui=5M4GH5ah=1js-+JvNFFLyCT*l@4mzlX1Qs@~DIyxkU"
form_secret: "8P;xPP^fMUn@oXMfEN+Kz7:tU._Pl3Ssuwz718HAnUF7w4oyz8"
signing_key_path: "/data/insa.lr.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"


# vim:ft=yaml

